---
- hosts: webserver
  remote_user: test
  become: yes
  tasks:
     - name: install httpd
       yum: name={{item}} state=installed
       with_items:
            - httpd
            - curl
            - lynx
            - telnet

