---
- hosts: webserver
  remote_user: test
  become: yes
  tasks:
     - name: install httpd
       yum: name=httpd state=installed
       tags:
          - install
     - name: create index.html file
       copy: src=index.html dest=/var/www/html
       tags:
          - create
     - name: start httpd service
       service: name=httpd state=started
       tags:
          - service 


