--- # Example of Tomcat Installation
- hosts: server2
  remote_user: test
  become: yes
  gather_facts: yes
  tasks:
     - name: install openjdk
       yum: name=java-1.8.0-openjdk state=installed
     - name: Remove older version of tomcat
       file: path=/usr/local/tomcat state=absent
     - name: Download Tomcat
       get_url: url=http://mirrors.estointernet.in/apache/tomcat/tomcat-7/v7.0.92/bin/apache-tomcat-7.0.92-deployer.tar.gz dest=/tmp  

     - name: create tomcat folder
     # command: mkdir /usr/local/tomcat
       file: path=/usr/local/tomcat state=directory
     - name: Extract archive
       unarchive: src=/tmp/apache-tomcat-7.0.92-deployer.tar.gz dest=/usr/local/tomcat copy=no
     - name: create tomcat users
       copy: src=/home/test/playbook/tomcat-users.xml dest=/usr/local/tomcat/apache-tomcat-7.0.92-deployer/conf/
     - name: deploy sample app
       copy: src=sample.war dest=/usr/local/tomcat/apache-tomcat-7.0.92-deployer/webapps
     - name: Start Tomcat
       command: nohup /usr/local/tomcat/apache-tomcat-7.0.92-deployer/bin/startup.sh &


